### ISSUE TITLE
Getting unknown property: yii\web\Application::c4ChangeLog

### ISSUE THREAD

**Issue by avbondarev** [Cranky4/change-log-behavior#1]
Hi! Method addLog cause an error: Getting unknown property: yii\web\Application::c4ChangeLog 
Where is the component "c4ChangeLog"?

**Comment by Cranky4** [comment]
Hello, are you sure you use the last version of this package? 1.0.6?
https://packagist.org/packages/cranky4/change-log-behavior

**Comment by avbondarev** [comment]
Да, скорее всего старая версия поставилась, из-за того что стоит 2.0.14.2
