### ISSUE TITLE
Docs update request

### ISSUE THREAD

**Issue by zealotrahl** [Cranky4/change-log-behavior#4]
use cranky4\ChangeLogBahavior\ListWidget;
use app\models\Post;

/**
 *  @var Post $model
 */
echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',
        'title',
        'rating',
        'created_at:datetime',
        'updated_at:datetime',
    ],
]);

echo ChangeLogList::widget([
    'model' => $model,
]);

Gives error not found class ChangeLogList, if we change to
echo ListWidget::widget([
    'model' => $model,
]);

 works correctly.

**Comment by Cranky4** [comment]
Updated
